### ISSUE TITLE
Broken and repeated links on Validation page

### ISSUE THREAD

**Issue by martinpub** [daisy/kb#80]
Hi,

On https://kb.daisy.org/publishing/docs/epub/validation/index.html, the links under the two headings "General" and "Validation" seem broken.

In addition, there is a duplicate set of links related to validation at the bottom of the page, without text blurbs. These are valid links.

**Comment by mattgarrish** [comment]
Thanks, there was a combination of a bad id and some old hard-coded links causing the full epub topic list to be generated. It should be fixed now.

**Comment by martinpub** [comment]
Thanks! It seems though that the links on https://kb.daisy.org/publishing/docs/epub/validation/index.html still get an extra "validation/" in the path.

**Comment by mattgarrish** [comment]
Ugh, yes. It's the only sub-topic that has an index page, so the script the generates the links wasn't accounting for already being in the folder. The other sub-topics default back to the overview pages rather than an index.

It should be fixed this time, though!

**Comment by martinpub** [comment]
Yes, verified fixed now. Thanks for the quick fix!
